### ISSUE TITLE
Spotify module

### ISSUE THREAD

**Issue by ghost** [doctorpiorno/jammming#1]
https://github.com/doctorpiorno/jammming/blob/master/src/util/Spotify.js

You've demonstrated a solid understanding of Promise-based APIs like `fetch` and have very strategically used ES6 template literals throughout your module to keep your code readable and maintainable 👍 

As a challenge to yourself, consider rewriting this module using `async/await`. You may find that you can shrink the size of your module and write more expressive and intuitive code. 

If you don't quite remember how `async` functions work, you can always revisit that material in our [JavaScript: Requests](https://www.codecademy.com/en/courses/intermediate-javascript-requests/lessons/requests-ii/exercises/async-get-requests-i) lesson.

**Comment by doctorpiorno** [comment]
Thanks. I'll have to refresh the `async / await` section as that whole part of the course is a bit of a blur, but I'll give it a look. As a suggestion: if `async / await` is more efficient, shouldn't the project instructions steer the students towards using them rather than `fetch`? I do remember my Spotify.js module being very unwieldy and hard to read towards the end, so much so that I went back to it and refactored it somewhat after submission.
